// Japanese copy for the language switch. Each key matches a data-i18n,
// data-i18n-aria-label, or data-i18n-alt attribute in the HTML (or a lookup in
// script.js). Furigana is written as {漢字|かんじ}, which script.js turns into
// <ruby>漢字<rt>かんじ</rt></ruby>. In the big headings, each <span> is a phrase
// that stays on one line when the heading wraps.
window.JA = {
    "skip": "{本文|ほんぶん}へスキップ",
    "nav.primary": "メイン",
    "nav.mobile": "モバイル",
    "nav.home": "Kian Hernando、ホーム",
    "nav.about": "{自己紹介|じこしょうかい}",
    "nav.projects": "プロジェクト",
    "nav.skills": "スキル",
    "nav.contact": "{連絡先|れんらくさき}",
    "lang.switch": "日本語",
    "menu.open": "メニューを開く",
    "menu.close": "メニューを閉じる",
    "resume": "{履歴書|りれきしょ}",
    "email": "メール",

    "home.title": "Kian Hernando | ソフトウェアエンジニア・コンピューターサイエンス専攻の学生",
    "hero.sr": "こんにちは、Kian Hernandoです。ソフトウェアエンジニアで、コンピューターサイエンスを専攻している学生です。",
    "hero.hi": "こんにちは、",
    "hero.typed": ["{開|かい}{発|はつ}{者|しゃ}です", "エンジニアです", "キアンです！"],
    "hero.bio": "CSUベーカーズフィールド{校|こう}でコンピューターサイエンスを{学|まな}びながら、みんなが{楽|たの}しく{使|つか}えるアプリやゲーム、ウェブサイトを{作|つく}っています。",
    "hero.projects": "プロジェクトを{見|み}る",
    "hero.contact": "{連絡|れんらく}する",

    "about.portrait": "レンガの壁の前で腕を組んで微笑むKian Hernandoのポートレート",
    "facts.university": "{大学|だいがく}",
    "facts.university.value": "カリフォルニア{州立大学|しゅうりつだいがく}ベーカーズフィールド{校|こう}",
    "facts.major": "{専攻|せんこう}",
    "facts.major.value": "コンピューターサイエンス",
    "facts.graduation": "{卒業予定|そつぎょうよてい}",
    "facts.graduation.value": "2027{年|ねん}5{月|がつ}",
    "facts.languages": "{言語|げんご}",
    "facts.languages.value": "{英語|えいご}、{日本語|にほんご}",
    "about.title": "{私|わたし}について",
    "about.p1": "2020{年|ねん}に{高校|こうこう}を{卒業|そつぎょう}した{後|あと}、CSUベーカーズフィールド{校|こう}で{看護学|かんごがく}を{学|まな}び{始|はじ}めました。しかし3{年|ねん}{経|た}った{頃|ころ}、{看護|かんご}では「{何|なに}かを{作|つく}りたい」という{気持|きも}ちが{満|み}たされないことに{気|き}づきました。じっくり{考|かんが}え、{友人|ゆうじん}の{勧|すす}めもあって、<strong>コンピューターサイエンス</strong>に{専攻|せんこう}を{変|か}えました。",
    "about.p2": "2023{年|ねん}の{秋学期|あきがっき}に{初|はじ}めてプログラミングの{授業|じゅぎょう}を{受|う}けて、すぐに{夢中|むちゅう}になりました。<strong>{実際|じっさい}に{使|つか}えるアプリやプログラム、ウェブサイトを{作|つく}ること</strong>が{大好|だいす}きで、プロジェクトが{難|むずか}しく{複雑|ふくざつ}になるほど、{解決|かいけつ}したくなります。<strong>チームで{協力|きょうりょく}すること</strong>も{大好|だいす}きです。{同|おな}じ{志|こころざし}を{持|も}つ{仲間|なかま}と{働|はたら}くと、{一人|ひとり}では{作|つく}れないものを{作|つく}るエネルギーが{湧|わ}いてきます。",
    "about.p3": "プログラミングと{学校|がっこう}{以外|いがい}では、{語学|ごがく}と{旅行|りょこう}が{大好|だいす}きです。{現在|げんざい}は{日本語|にほんご}を{勉強|べんきょう}していて、{日本|にほん}に{留学|りゅうがく}する{予定|よてい}です。これまでにカナダ、メキシコ、フィリピン、{韓国|かんこく}、タイにも{行|い}ったことがあります。{家|いえ}にいるときは、ゲームをしたり、{友達|ともだち}や{家族|かぞく}と{過|す}ごしたりしています。",
    "about.p4": "{現在|げんざい}、<strong>ソフトウェアエンジニアのインターンシップ</strong>を{探|さが}しています。<strong>スピード{感|かん}のある{環境|かんきょう}</strong>で{意欲的|いよくてき}なチームの{働|はたら}き{方|かた}を{学|まな}びながら、{人|ひと}の{役|やく}に{立|た}つプロジェクトを{作|つく}り{続|つづ}けたいです。",

    "projects.title": "<span>これまでに</span><span>{作|つく}ったもの</span>",
    "projects.more": "GitHubでもっと{見|み}る",
    "tags.label": "使用技術",
    "kind.live": "{公開中|こうかいちゅう}のウェブアプリ",
    "kind.game": "ゲーム",
    "kind.web": "ウェブアプリ",
    "quickqr.desc": "{静的|せいてき}・{動的|どうてき}なQRコードを{生成|せいせい}し、デザインをカスタマイズして、スキャンごとの{統計|とうけい}を{追跡|ついせき}できます。",
    "janken.desc": "すべてのバトルがじゃんけんで{決|き}まる2Dターン{制|せい}RPG。C++、OpenGL、X11で{開発|かいはつ}しました。",
    "tcg.desc": "APIのリアルタイムデータから{作|つく}られるポケモンカードのパックを{開封|かいふう}できるシミュレーター。{色違|いろちが}いも{登場|とうじょう}し、{引|ひ}いたカードはコレクションに{保存|ほぞん}できます。",
    "typr.desc": "リアルタイムの{正確率|せいかくりつ}{表示|ひょうじ}、{単語数|たんごすう}の{調整|ちょうせい}、キーボードの{打鍵音|だけんおん}を{備|そな}えたミニマルなタイピングテスト。",

    "skills.title": "{技術|ぎじゅつ}スタック",
    "skills.languages": "プログラミング{言語|げんご}",
    "skills.frameworks": "フレームワークとライブラリ",
    "skills.tools": "{開発|かいはつ}ツール",

    "contact.title": "<span>{一緒|いっしょ}に{何|なに}か</span><span>{作|つく}りましょう！</span>",
    "contact.line1": "ソフトウェアエンジニアとしての{機会|きかい}や、{新|あたら}しいプロジェクトのご{相談|そうだん}をいつでもお{待|ま}ちしています！",
    "contact.line2": "いつでもお{気軽|きがる}にメールしてください！",
    "copy": "コピー",
    "copy.label": "メールアドレスをコピー",
    "copy.done": "コピーしました",
    "copy.manual": "Ctrl+Cを{押|お}す",
    "copy.status.done": "メールアドレスをクリップボードにコピーしました。",
    "copy.status.failed": "自動でコピーできませんでした。アドレスを選択してコピーしてください。",

    "case.back": "プロジェクト{一覧|いちらん}",
    "case.role": "{役割|やくわり}",
    "case.timeline": "{期間|きかん}",
    "case.team": "チーム",
    "case.stack": "{使用技術|しようぎじゅつ}",
    "case.wip": "{準備中|じゅんびちゅう}",
    "case.source": "ソースコードを{見|み}る",
    "case.toc": "{目次|もくじ}",
    "case.toc.label": "目次",
    "case.overview": "{概要|がいよう}",
    "case.problem": "{課題|かだい}",
    "case.built": "{作|つく}ったもの",
    "case.highlights": "{技術的|ぎじゅつてき}なポイント",
    "case.learned": "{学|まな}んだこと",
    "case.gallery": "ギャラリー",
    "case.next": "{次|つぎ}のプロジェクト",
    "video.play": "動画を再生",
    "video.pause": "動画を一時停止",

    "quickqr.title": "QuickQR：動的QRコードジェネレーター | Kian Hernando",
    "quickqr.lede": "{静的|せいてき}・{動的|どうてき}なQRコードの{作成|さくせい}、デザインのカスタマイズ、スキャンの{追跡|ついせき}ができるQRコードプラットフォーム。",
    "quickqr.visit": "quickqr.appを{開|ひら}く",
    "quickqr.video": "QuickQRの画面録画",
    "quickqr.overview": "QuickQRは、{外部|がいぶ}APIを{利用|りよう}して<strong>{静的|せいてき}・{動的|どうてき}なQRコード</strong>を{生成|せいせい}するツールで、コードの{見|み}た{目|め}を{自由|じゆう}にカスタマイズできます。ログインしたユーザーは、{利用状況|りようじょうきょう}を{追跡|ついせき}し、スキャンごとの{統計|とうけい}を{確認|かくにん}できます。",
    "quickqr.built1": "<strong>{静的|せいてき}・{動的|どうてき}コード。</strong>コードは{外部|がいぶ}APIで{生成|せいせい}され、{動的|どうてき}コードは{印刷後|いんさつご}でもリンク{先|さき}を{変更|へんこう}できます。",
    "quickqr.built2": "コードの{見|み}た{目|め}を<strong>{自由|じゆう}にカスタマイズ</strong>。",
    "quickqr.built3": "<strong>スキャン{分析|ぶんせき}。</strong>すべてのコードがスキャンを{記録|きろく}し、コードごとの{統計|とうけい}を{確認|かくにん}できます。",
    "quickqr.built4": "{有効|ゆうこう}・{期限切|きげんぎ}れのコードを{管理|かんり}する<strong>ダッシュボード</strong>。{検索|けんさく}、スキャン{数|すう}、コードごとの{操作|そうさ}に{対応|たいおう}。",
    "quickqr.built5": "{設定|せってい}ページと{請求|せいきゅう}ページを{備|そな}えた<strong>アカウント{機能|きのう}</strong>。",

    "janken.title": "ジャンケン: A One-Handed Journey – C++製RPG | Kian Hernando",
    "janken.lede": "すべての{戦|たたか}いがじゃんけんで{決|き}まる2Dターン{制|せい}RPG。",
    "janken.timeline": "2025{年|ねん}{春|はる}",
    "janken.team": "5{名|めい}",
    "janken.video": "ジャンケンの画面録画",
    "janken.overview1": "{片手|かたて}だけの{主人公|しゅじんこう}ハンデルは、{目|め}を{覚|さ}ますと{腕|うで}から{切|き}り{離|はな}されていて、{失|うしな}った{体|からだ}を{探|さが}す{旅|たび}に{出|で}ます。ジャンケンは、<strong>MOTHER</strong>、<strong>ドラゴンクエスト</strong>、<strong>UNDERTALE</strong>シリーズにインスパイアされた2Dターン{制|せい}RPGで、じゃんけんをベースにした{戦闘|せんとう}システムが{特徴|とくちょう}です。",
    "janken.overview2": "ただし、チャンスは{一度|いちど}きり。",
    "janken.problem": "このゲームには{厳|きび}しい{制約|せいやく}がありました。",
    "janken.problem1": "ゲームロジックはすべて<strong>C++</strong>で{記述|きじゅつ}。",
    "janken.problem2": "グラフィックスは<strong>OpenGL</strong>と<strong>X11</strong>プロトコル、オーディオは<strong>OpenAL</strong>を{使用|しよう}。",
    "janken.problem3": "Gordon Griesel{氏|し}の<em>background</em>フレームワークをベースに{構築|こうちく}。",
    "janken.problem4": "サイズは{最大|さいだい}<strong>5 MB</strong>まで。",
    "janken.built1": "{全|ぜん}20レベルの<strong>ラウンド{制|せい}バトル</strong>。{攻撃|こうげき}の{順番|じゅんばん}はじゃんけんで{決|き}まります。",
    "janken.built2": "プレイヤーと{敵|てき}の{両方|りょうほう}に<strong>{体力|たいりょく}とダメージのステータス</strong>。",
    "janken.built3": "<strong>アニメーションするプレイヤーモデル</strong>と{動|うご}く{背景|はいけい}。",
    "janken.built4": "{出会|であ}う{敵|てき}ごとに<strong>{固有|こゆう}のスプライトとセリフ</strong>。",
    "janken.built5": "すべての{操作|そうさ}に{対応|たいおう}した<strong>キーボード{操作|そうさ}のGUI</strong>。",
    "janken.next": "{次|つぎ}の{目標|もくひょう}は、スコアに{応|おう}じた{報酬|ほうしゅう}システムとセーブ{機能|きのう}です。",

    "tcg.title": "Pokémon TCG Pack Opener – React製ウェブアプリ | Kian Hernando",
    "tcg.lede": "ポケモンカードのパック{開封|かいふう}シミュレーター。{色違|いろちが}いも{登場|とうじょう}し、コレクションを{保存|ほぞん}できます。",
    "tcg.timeline": "2024{年|ねん}{秋|あき}",
    "tcg.team": "2{名|めい}",
    "tcg.video": "TCG Pack Openerの画面録画",
    "tcg.overview": "ポケモンカードのパック{開封|かいふう}を{再現|さいげん}したシミュレーターで、{外部|がいぶ}の<strong>PokeAPI</strong>と{連携|れんけい}してカードを{生成|せいせい}・{収集|しゅうしゅう}できます。カードは<strong>{色違|いろちが}い</strong>で{出|で}ることもあり、それぞれの{属性|ぞくせい}も{表示|ひょうじ}されます。",
    "tcg.built1": "PokeAPIのデータからカードを{生成|せいせい}する<strong>パック{開封|かいふう}</strong>。",
    "tcg.built2": "<strong>{色違|いろちが}い</strong>とカードごとの{属性|ぞくせい}。",
    "tcg.built3": "{認証|にんしょう}とコレクション{保存|ほぞん}に{対応|たいおう}した<strong>ユーザーアカウント</strong>。",

    "typr.title": "typr.：ミニマルなタイピング速度テスト | Kian Hernando",
    "typr.lede": "Monkeytypeにインスパイアされた、ミニマルなウェブタイピングテスト。",
    "typr.try": "typr.を{試|ため}す",
    "typr.video": "typr.の画面録画",
    "typr.overview": "typr.は、Monkeytypeのようなウェブ{上|じょう}のタイピング{速度|そくど}テストで、HTML、CSS、JavaScriptだけで{作|つく}りました。{単語|たんご}に{集中|しゅうちゅう}できるよう、インターフェースはミニマルにしています。",
    "typr.built1": "{入力中|にゅうりょくちゅう}の<strong>リアルタイム{正確率|せいかくりつ}{表示|ひょうじ}</strong>。",
    "typr.built2": "{短|みじか}いテストにも{長|なが}いテストにも{対応|たいおう}できる<strong>{単語数|たんごすう}の{設定|せってい}</strong>。",
    "typr.built3": "<strong>キーボードの{打鍵音|だけんおん}。</strong>",
    "typr.built4": "{邪魔|じゃま}にならない<strong>ミニマルなUI</strong>。",
};
